### ISSUE TITLE
Add event listner for dropdown component

### ISSUE THREAD

**Issue by haridusenadeera** [dictyBase/reactTest#6]
Dropdown menu has to disappear when a click occurs inside the document (outside of the dropdown menu component).

**Comment by haridusenadeera** [comment]
02a7c0840d3c876b577cef074323d04a9c0f1d0f

**Comment by haridusenadeera** [comment]
The following code seems to work. (https://github.com/dictyBase/reactTest/blob/dropdownTest2/src/scripts/components/NavbarDropdown.jsx) 
However when one dropdown menu is open, and if you click on another dropdown menu, the dropdown menu that is already open does not close. 

![navbar](https://cloud.githubusercontent.com/assets/12897928/9826920/5d3cda9e-58a3-11e5-852d-1254731e18b1.jpg)


    setDropdownState =(newState) => {
      this.setState({
        open: newState
      });
    }

    handleDocumentClick = () => {
      this.setDropdownState(false);
    }

    handleDropdownClick = (e) => {
      e.preventDefault();
      e.nativeEvent.stopImmediatePropagation();
      this.setDropdownState(!this.state.open);
    }

    componentDidMount() {
      document.addEventListener('click', this.handleDocumentClick);
    }

    componentWillUnmount() {
      document.removeEventListener('click', this.documentClickHandler);
    }

    render() {
      const {style, name} = this.props;
      const defStyle = this.getStyles();
      return (
        <li ref= "dropdown" style={[defStyle.dropdown, style && style]}>
            <a ref="link" onClick={this.handleDropdownClick} href="#" style={[defStyle.link]}>
                {name}{' '}
                <b style={[defStyle.caret]}></b>
            </a>
            {this.renderChildren()}
        </li>
      );
    }

**Comment by cybersiddhu** [comment]
The behaviour is that only one `dropdown` should be open at a time. For that, if one dropdown is clicked any other open dropdown has to be closed. To implement that, all dropdown has to be notified of the click on any single dropdown which means the state has to be shifted to the parent `NavbarItems`.

**Comment by haridusenadeera** [comment]
Thanks for your feedback! I will start working on that.

**Comment by cybersiddhu** [comment]
Just to make sure you understand, its going to be little tricky to do, you really have to have a good concept about state and props to pull it off.

**Comment by cybersiddhu** [comment]
Check out the above branch/commit, should resolve all the problems.
It works fine in my machine, but in any case test it out as much you could, then go through all the commits i made,
make a self pull request and merge it. 
Try to read the code and see if you understand the logic behind it.

**Comment by cybersiddhu** [comment]
![nav](https://cloud.githubusercontent.com/assets/48740/9860426/bc886a2c-5af1-11e5-8d1e-289eb58b86ba.gif)

**Comment by haridusenadeera** [comment]
Awesome! It works on mine too. Thank you! I will test it out more. And I have to go over the code to understand the logic.

**Comment by haridusenadeera** [comment]
#7 solves the issue.
