### ISSUE TITLE
Create responsive navbar

### ISSUE THREAD

**Issue by haridusenadeera** [dictyBase/reactTest#8]
## Components
    <Navbar>
        <NavbarHeader href="homepage.html" name="Navbar Brand"/>
        <NavbarItems>
            <Item link={"#"} title={About} />;
            <Item link={"#"} title={Contact} />;
            <NavbarDropdown name="Dropdown">
                <DropdownMenu menuItems={dropdownItems}/>
            </NavbarDropdown>
            <NavbarDropdown name="Dropdown">
                <DropdownMenu menuItems={dropdownItems}/>
            </NavbarDropdown>
        </NavbarItems>
    </Navbar>

### NavbarHeader Component
    navbarToggle = () => {

       // on click, the following styles must be set to <NavbarItems> component 
      //  to open the responsive view dropdown.

       display: block;
       overflow-y: auto;
         @media (min-width: 768px) {
           overflow-y: visible;
         }
    }

    render () {
      const defStyle = this.getStyles();
      const {href, name, headerStyle, brandStyle} = this.props;

      return {
        <div key="header" style= {[defStyle.header, headerStyle && headerStyle]}>
          <span style= {[defStyle.pseudoBefore]} />
              <button type="button" style= {[defStyle.navbarToggle]} onClick= {this.navbarToggle}>
                  <span style= {[defStyle.srOnly]}>Toggle navigation</span>
                  <span style= {[defStyle.iconBar]}></span>
                  <span style= {[defStyle.iconBar, defStyle.burger]}></span>
                  <span style= {[defStyle.iconBar, defStyle.burger]}></span>
              </button>
              <a key="brand" style= {[defStyle.brand, brandStyle && brandStyle]} href= {href}>
                  {name}
              </a>
          <span style= {[defStyle.pseudoAfter]} />
        </div>
      };
    }

Communication between siblings (`<NavbarHeader>` & `<NavbarItems>`) must be established to achieve the navbar responsive view. 

### NavbarItems Component
    render() {
      const defStyle = this.getStyles();
      const {style} = this.props;

      return (
          <div ref ="collapse" style={[defStyle.collapse]}>
              <span style={[defStyle.pseudoBefore]} />
                  <ul ref="navitems" style={[defStyle.base, style && style]}>
                      <span style={[defStyle.pseudoBefore]} />
                        {this.renderChildren()}
                      <span style={[defStyle.pseudoAfter]} />
                  </ul>
              <span style={[defStyle.pseudoAfter]} />
          </div>
      );
    }

Below is the default behavior of bootstrap navbar responsive view.

![navbar](https://cloud.githubusercontent.com/assets/12897928/10084343/9e2eab84-62c8-11e5-943e-6c303a72d11c.gif)

**Comment by haridusenadeera** [comment]
ToDo: 
- [x] bc066fdd137d3a8a7ef9333f03fd444bef1d4a04 added navbar toggle
- [ ] NavbarDropdown in responsive view

**Comment by cybersiddhu** [comment]
Please link all commits related to this issue.
Also could you write down the logic for creating the responsive bar.

**Comment by haridusenadeera** [comment]
Commits related to the issue: 
ef3174b1958df8f472df587222dabaf98700549c - changed `container-fluid` to `container`
df43131a66740a59ee0210d16f6ef6e96caf2838 - added `navbar-toggle` button and styles
bc066fdd137d3a8a7ef9333f03fd444bef1d4a04 - added `navbar-toggle` onClick function

**Comment by haridusenadeera** [comment]
`<NavbarItems>` is hidden (`display:none`) when the navbar is in responsive view (width < 768px) and, `navbar-toggle` button displays (It is hidden when the navbar is more than 768px width)

In responsive view (width < 768px), `<NavbarItems>` list is <strong>not</strong> displayed inline.

`navbar-toggle` button is grouped with `navbar-brand` in the `<NavbarHeader>` component.

In responsive view, navbar looks like this:

![navbarcollapsed](https://cloud.githubusercontent.com/assets/12897928/10124167/0a7a3450-6514-11e5-8d77-2f23c68dc078.jpg)

Now, when the user clicks on the `navbar-toggle` button (which is in the `<NavbarHeader>` component), `<NavbarItems>` must display: block. 

![navbarcomponents](https://cloud.githubusercontent.com/assets/12897928/10124400/fbadec04-6519-11e5-967b-f7805dfa709b.png)

To do this, I've created a parent call back function which lets `<NavbarItems>` know when a user clicks on the `navbar-toggle` button. bc066fdd137d3a8a7ef9333f03fd444bef1d4a04

**Comment by haridusenadeera** [comment]
# Navigation bar tree structure
![navbartree](https://cloud.githubusercontent.com/assets/12897928/10143922/7c0a56f0-65e0-11e5-85f1-8494fb430868.jpg)
